
//登录
export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS'
export const LOGIN_STATUS_NO = 'NO_LOGIN'
export const LOGIN_STATUS_HAS = 'HAS_LOGIN'


//index 
export const CHANGE_HEADER_SHOW = 'CHANGE_HEADER_SHOW'
export const AREA_AND_TYPE_SELECT = 'AREA_AND_TYPE_SELECT'
export const CHANGE_INDUSTRY_NAV_COM = 'CHANGE_INDUSTRY_NAV_COM'



//home
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST'
export const CHANGE_STUDY_NAV_CON = 'CHANGE_STUDY_NAV_CON'
export const CHANGE_STUDY_ALL_LIST = 'CHANGE_STUDY_ALL_LIST'


//record
export const MY_EDUCOLLECT = 'MY_EDUCOLLECT'

//selectTopic
export const SAVE_SELECT_TOPIC_ITEM = 'SAVE_SELECT_TOPIC_ITEM'
export const GET_IBANK_LIST = 'GET_IBANK_LIST'
export const SAVE_ALL_ANSWERS = 'SAVE_ALL_ANSWERS'
export const CLEAR_ALL_ANSWERS = 'CLEAR_ALL_ANSWERS'
export const SAVE_START_TIME = 'SAVE_START_TIME'
export const GET_ERROR_IBANK_LIST = 'GET_ERROR_IBANK_LIST'
export const GET_TEST_LIST_BY_ID = 'GET_TEST_LIST_BY_ID'




//SEARCH
export const SEARCH_ARTICLE_LIST = 'SEARCH_ARTICLE_LIST'
